### ISSUE TITLE
str/bytes/encoding problems on Windows

### ISSUE THREAD

**Issue by cfbao** [google/adb-sync#10]
- On Windows, subprocess.Popen process arguments as strings, and problem arises when bytes are passed in (a bytes-like object is required, not 'str').
- Python 3.6 now uses UTF-8 for Windows filesystem and console encoding. Using locale.getdefaultlocale()[1] is not appropriate in this case.

I modified the script, changing all bytes to str and using UTF-8 only, and got a working script on my system (Win 7, Python 3.6), but it probably doesn't work on many other systems. Would love to see this tool improved in this regard.

**Comment by bohwaz** [comment]
Yup no support for anything else than ASCII here, fails on Linux too. This sucks.

**Comment by maik-s** [comment]
hey @cfbao i ran into the exactly same problem and would appreciate it if you would share your modified script.

**Comment by Marco3456** [comment]
Hello,
I also have the same problem but I' m not familiar with Python so I'm not able to modify the script myself. Are there any other solutions or will this problem be fixed in the future? I love this tool and I would be happy to use it again.

I'm using Windows 10, Python 3.7.2 and the latest version of the script.
Here's the error message:

`C:\Users\Marco>adb-sync --reverse /sdcard/DCIM/Camera ~/Downloads
INFO:root:Sync: local b'~/Downloads/Camera', remote b'/sdcard/DCIM/Camera'
Traceback (most recent call last):
  File "C:\Users\Marco\Desktop\adb-sync-master\adb-sync.py", line 883, in <module>
    main()
  File "C:\Users\Marco\Desktop\adb-sync-master\adb-sync.py", line 870, in main
    if not syncer.IsWorking():
  File "C:\Users\Marco\Desktop\adb-sync-master\adb-sync.py", line 507, in IsWorking
    return self.adb.IsWorking()
  File "C:\Users\Marco\Desktop\adb-sync-master\adb-sync.py", line 221, in IsWorking
    b'date +%s' % (self.QuoteArgument(test_string),)]) as stdout:
  File "C:\Users\Marco\Desktop\adb-sync-master\adb-sync.py", line 76, in __init__
    self.popen = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'`

Thanks in advance!
