### ISSUE TITLE
TypeError with latest rev

### ISSUE THREAD

**Issue by Flow86** [google/adb-sync#36]
I get this error with rev fb7c549
```
# adb-sync/adb-sync -s b780df65 -R /storage/emulated/0/ backup/storage/emulated/0/
INFO:root:Sync: local b'backup/storage/emulated/0/', remote b'/storage/emulated/0/'
Traceback (most recent call last):
  File "adb-sync/adb-sync", line 883, in <module>
    main()
  File "adb-sync/adb-sync", line 870, in main
    if not syncer.IsWorking():
  File "adb-sync/adb-sync", line 507, in IsWorking
    return self.adb.IsWorking()
  File "adb-sync/adb-sync", line 221, in IsWorking
    b'date +%s' % (self.QuoteArgument(test_string),)]) as stdout:
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```

```
# python3 --version
Python 3.4.2
```

**Comment by Flow86** [comment]
Ah I've found out it seems my python 3.4 is too old.
