### ISSUE TITLE
Does not work on MAC

### ISSUE THREAD

**Issue by MrThiago** [google/adb-sync#7]
I am trying to use this on mac:
I am getting this error:

adb-sync ../COPY_TEST/ mnt/sdcard/
Traceback (most recent call last):
  File "/usr/local/bin/adb-sync", line 774, in <module>
    main(*sys.argv)
  File "/usr/local/bin/adb-sync", line 693, in main
    args_encoding = locale.getdefaultlocale()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

can anyone help please

**Comment by ngyikp** [comment]
Try https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python

**Comment by divVerent** [comment]
locale.getdefaultlocale() failing seems to be a Python bug to me, not an adb-sync bug.

Does the workaround on coderwall.com work for you? It might be possible to put this into adb-sync itself, as a hack.

**Comment by MrThiago** [comment]
I managed to get it working.
Big thanks guys.
